export const types = {
  FETCH_BLOG_REQUEST: 'FETCH_BLOG_REQUEST',
  FETCH_BLOG_SUCCESS: 'FETCH_BLOG_SUCCESS',
  FETCH_BLOG_FAILURE: 'FETCH_BLOG_FAILURE',

  FETCH_BLOG_DETAIL_REQUEST: 'FETCH_BLOG_DETAIL_REQUEST',
  FETCH_BLOG_DETAIL_SUCCESS: 'FETCH_BLOG_DETAIL_SUCCESS',
  FETCH_BLOG_DETAIL_FAILURE: 'FETCH_BLOG_DETAIL_FAILURE',
};
